### ISSUE TITLE
%functions% role not working when a model is specified in command line

### ISSUE THREAD

**Issue by tomsib2001** [sigoden/llm-functions#9]
When I specify a model, the function calling seems to stop working:

```
thomas@[HOSTNAME]:~/projets/llm-functions$ aichat -r %functions% print the millionth prime in python
Call may_execute_py_code '{"code":"import sympy\nprint(sympy.prime(1000000))"}'
> [1] Run, [2] Run & Retrieve, [3] Skip: 1
15485863
thomas@[HOSTNAME]:~/projets/llm-functions$ aichat  --model azure_ai:gpt-4-turbo-1106-preview -r %functions% print the millionth prime in python
Generating the millionth prime number can be achieved in Python by implementing a prime number finding algorithm. Below is [etc]
```

**Comment by sigoden** [comment]
Only models that support function calling can use function calling.

You can check if your model supports function calling by using the `.model <tab>`  autocompletion in the REPL.
![image](https://github.com/sigoden/llm-functions/assets/4012553/e1c774c5-5f2d-4818-bd1a-7031db8ccdd5)

> Models with `⚒` have function calling capabilities.

Adding the following configuration to the model lets AIChat know it supports function calling.
```yaml
      supports_function_calling: true
```

https://github.com/sigoden/aichat/blob/5458150ed3203cf13b0371efa2c791ac696cee93/models.yaml#L25-L31

**Comment by tomsib2001** [comment]
Thanks for your answer! I had not understood that the `supports_function_calling: true` was needed on top of the documented `function_calling: true`. Are both necessary ?

**Comment by sigoden** [comment]
```yaml
function_calling: true
clients:
- type: <some client> 
  models:
    - name: <some model>
      supports_function_calling: true
```

**Comment by zhh210** [comment]
Does this solution still work (for version 0.29.0)? I've added `function_calling: true` and `supports_function_calling: true` to ~/.config/aichat/config.yaml:
```
model: github-copilot:gpt-4o
function_calling: true
clients:
- type: openai-compatible
  name: github-copilot
  api_base: <api_base>
  api_key: <api_key>
  models:
  - name: gemini-2.0-flash-001
  - name: gpt-3.5-turbo
  - name: gpt-3.5-turbo-0613
  - name: gpt-4
    max_input_tokens: 128000
    max_output_tokens: 4096
    input_price: 5
    output_price: 15
    supports_vision: true
    supports_function_calling: true
  - name: gpt-4-0613
  - name: gpt-4-o-preview
  - name: gpt-4o
    max_input_tokens: 128000
    max_output_tokens: 4096
    input_price: 5
    output_price: 15
    supports_vision: true
    supports_function_calling: true
```
 and .model confirms so:

```
> | .model github-copilot:g
github-copilot:gemini-2.0-flash-001           - /        -  |       - /      -        
github-copilot:gpt-3.5-turbo                  - /        -  |       - /      -        
github-copilot:gpt-3.5-turbo-0613             - /        -  |       - /      -        
github-copilot:gpt-4                     128000 /     4096  |       5 /     15    👁 ⚒ 
github-copilot:gpt-4-0613                     - /        -  |       - /      -        
github-copilot:gpt-4-o-preview                - /        -  |       - /      -        
github-copilot:gpt-4o                    128000 /     4096  |       5 /     15    👁 ⚒ 

```
However, neither of the two models are able to call functions:
```
$ argc mcp start
Start MCP Bridge server...
Merge MCP tools into functions.json
Build bin/trino_execute_sql
Build bin/sqlalchemy_all_table_names
Build bin/sqlalchemy_filter_table_names
Build bin/sqlalchemy_schema_definitions
Build bin/sqlalchemy_execute_query
Build bin/filesystem_read_file
Build bin/filesystem_read_multiple_files
Build bin/filesystem_write_file
Build bin/filesystem_edit_file
Build bin/filesystem_create_directory
Build bin/filesystem_list_directory
Build bin/filesystem_directory_tree
Build bin/filesystem_move_file
Build bin/filesystem_search_files
Build bin/filesystem_get_file_info
Build bin/filesystem_list_allowed_directories

$ aichat -m github-copilot:gpt-4o --role %functions% what is the weather in Paris?
I'm sorry, but I can't provide real-time information such as current weather conditions. You can check the latest weather updates for Paris on a weather forecasting website or app.
$ aichat -m github-copilot:gpt-4 --role %functions% what is the weather in Paris?
I'm unable to provide real-time information or updates. To get the current weather in Paris, I recommend checking a reliable weather website or app, such as the Weather Channel, BBC Weather, or a similar service.

```
